/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancoso;

import java.awt.Image;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Enrique
 */
public class Cuenta extends javax.swing.JFrame {

    Icon icon = new ImageIcon(getClass().getResource("IC2.png"));

    public Cuenta() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("IC.png")).getImage();
        setIconImage(icon);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Banco - BBVA");
        txtCuenta.setEditable(false);
        txtNIP.setEditable(false);
        Tipo();
    }

    public void Tipo() {
        int fin = 0;
        
        //Consulta el valor maximo del rango para generar numero de cuenta
        try {
            Statement stm = new Conexion().Conexion().createStatement();
            ResultSet rs = stm.executeQuery("select max(fin) as valor from tclientes");
            while (rs.next()) {
                fin = rs.getInt("valor");
            }
        } catch (Exception e) {
        }
        String cuenta = "", nip = "";
        for (int i = 0; i < 12; i++) {
            cuenta += (int) Math.floor(Math.random() * (10));
        }
        cuenta += validacion(fin);//Concatena los doce digitos iniciales con los 4 especiales
        for (int i = 0; i < 4; i++) {
            nip += (int) Math.floor(Math.random() * (10));
        }
        txtCuenta.setText(cuenta);
        txtNIP.setText(nip);
    }

    //Metodo para generar los ultimos digitos de la cuenta
    public String validacion(int fin) {
        String a = "";
        do {
            a = "";
            for (int j = 0; j < 4; j++) {
                a += (int) Math.floor(Math.random() * (10));
            }
        } while (Integer.parseInt(a) > fin);
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new org.edisoncor.gui.panel.PanelImage();
        pnlNIP = new org.edisoncor.gui.panel.PanelImage();
        pnlUS2 = new org.edisoncor.gui.panel.PanelImage();
        txtNombre = new app.bolivia.swing.JCTextField();
        pnlUsuario = new org.edisoncor.gui.panel.PanelImage();
        pnlUS = new org.edisoncor.gui.panel.PanelImage();
        txtNIP = new app.bolivia.swing.JCTextField();
        btnInicio = new javax.swing.JButton();
        pnlUsuario2 = new org.edisoncor.gui.panel.PanelImage();
        txtCuenta = new app.bolivia.swing.JCTextField();
        pnlUS3 = new org.edisoncor.gui.panel.PanelImage();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/BBVA1.png"))); // NOI18N

        pnlNIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        pnlUS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/US.png"))); // NOI18N
        pnlUS2.setInheritsPopupMenu(true);

        javax.swing.GroupLayout pnlUS2Layout = new javax.swing.GroupLayout(pnlUS2);
        pnlUS2.setLayout(pnlUS2Layout);
        pnlUS2Layout.setHorizontalGroup(
            pnlUS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUS2Layout.setVerticalGroup(
            pnlUS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        txtNombre.setBorder(null);
        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombre.setPlaceholder("Nombre");

        javax.swing.GroupLayout pnlNIPLayout = new javax.swing.GroupLayout(pnlNIP);
        pnlNIP.setLayout(pnlNIPLayout);
        pnlNIPLayout.setHorizontalGroup(
            pnlNIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNIPLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(pnlUS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlNIPLayout.setVerticalGroup(
            pnlNIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNIPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlUS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        pnlUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/PW.png"))); // NOI18N

        javax.swing.GroupLayout pnlUSLayout = new javax.swing.GroupLayout(pnlUS);
        pnlUS.setLayout(pnlUSLayout);
        pnlUSLayout.setHorizontalGroup(
            pnlUSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUSLayout.setVerticalGroup(
            pnlUSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        txtNIP.setBorder(null);
        txtNIP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNIP.setPlaceholder("NIP");

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnlUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnInicio.setBackground(new java.awt.Color(177, 213, 231));
        btnInicio.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        pnlUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        txtCuenta.setBorder(null);
        txtCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCuenta.setPlaceholder("Cuenta");

        pnlUS3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/US.png"))); // NOI18N

        javax.swing.GroupLayout pnlUS3Layout = new javax.swing.GroupLayout(pnlUS3);
        pnlUS3.setLayout(pnlUS3Layout);
        pnlUS3Layout.setHorizontalGroup(
            pnlUS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUS3Layout.setVerticalGroup(
            pnlUS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlUsuario2Layout = new javax.swing.GroupLayout(pnlUsuario2);
        pnlUsuario2.setLayout(pnlUsuario2Layout);
        pnlUsuario2Layout.setHorizontalGroup(
            pnlUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuario2Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlUsuario2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(pnlUS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(308, Short.MAX_VALUE)))
        );
        pnlUsuario2Layout.setVerticalGroup(
            pnlUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuario2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnlUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlUsuario2Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlUS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnRegistrar.setBackground(new java.awt.Color(177, 213, 231));
        btnRegistrar.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(pnlUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        new Admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            if (txtNombre.equals("") || txtCuenta.equals("") || txtNIP.equals("")) {
                JOptionPane.showMessageDialog(null, "<html><h2>Campos Incompletos</h2></html>",
                        "Banco - BBVA", JOptionPane.INFORMATION_MESSAGE, icon);
            } else {
                Statement stm = new Conexion().Conexion().createStatement();
                cliente(txtCuenta.getText());//Metodo de registro

                stm.executeUpdate("insert into Usuarios(cuenta,nip,saldo,nombre,tipo) values(\'" + txtCuenta.getText() + "\',\'" + txtNIP.getText() + "\',0,\'" + txtNombre.getText() + "\',\'U\')");
                JOptionPane.showMessageDialog(null, "<html><h2>Cuenta Registrada</h2></html>",
                        "Banco - BBVA", JOptionPane.INFORMATION_MESSAGE, icon);
                new Cuenta().setVisible(true);
                this.setVisible(false);
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    //Metodo Agregado para Insertar Tipo de Clientes
    public void cliente(String cuenta) {
        try {
            Statement stm = new Conexion().Conexion().createStatement();
            Statement stm3 = new Conexion().Conexion().createStatement();
            ResultSet rs2 = stm3.executeQuery("select * from TClientes");
            while (rs2.next()) {
                int inicio = rs2.getInt("Inicio");
                int fin = rs2.getInt("Fin");
                String tipo = rs2.getString("Tipo");
                int dato=Integer.parseInt(txtCuenta.getText().substring(12, 16));
                if ( dato<= fin&& dato >= inicio) {
                    stm.executeUpdate("insert into " + tipo + "(cuenta,nombre) values(\'" + cuenta + "\',\'" + txtNombre.getText() + "\')");
                }
            }
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegistrar;
    private org.edisoncor.gui.panel.PanelImage pnlNIP;
    private org.edisoncor.gui.panel.PanelImage pnlPrincipal;
    private org.edisoncor.gui.panel.PanelImage pnlUS;
    private org.edisoncor.gui.panel.PanelImage pnlUS1;
    private org.edisoncor.gui.panel.PanelImage pnlUS2;
    private org.edisoncor.gui.panel.PanelImage pnlUS3;
    private org.edisoncor.gui.panel.PanelImage pnlUsuario;
    private org.edisoncor.gui.panel.PanelImage pnlUsuario1;
    private org.edisoncor.gui.panel.PanelImage pnlUsuario2;
    private app.bolivia.swing.JCTextField txtCuenta;
    private app.bolivia.swing.JCTextField txtCuenta1;
    private app.bolivia.swing.JCTextField txtNIP;
    private app.bolivia.swing.JCTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
