/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancoso;

import static bancoso.Relleno.c100;
import static bancoso.Relleno.c1000;
import static bancoso.Relleno.c20;
import static bancoso.Relleno.c200;
import static bancoso.Relleno.c50;
import static bancoso.Relleno.c500;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Enrique
 */
public class Deposito extends javax.swing.JFrame {

    Icon icon = new ImageIcon(getClass().getResource("IC2.png"));
    public static int c20 = 0, c50 = 0, c100 = 0, c200 = 0, c500 = 0, c1000 = 0;
    public static int ca20 = 0, ca50 = 0, ca100 = 0, ca200 = 0, ca500 = 0, ca1000 = 0;

    public Deposito() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("IC.png")).getImage();
        setIconImage(icon);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Banco - BBVA");
        txt20.setText(String.valueOf(c20));
        txt50.setText(String.valueOf(c50));
        txt100.setText(String.valueOf(c100));
        txt200.setText(String.valueOf(c200));
        txt500.setText(String.valueOf(c500));
        txt1000.setText(String.valueOf(c1000));
        ca20=Contar(20);
        ca50=Contar(50);
        ca100=Contar(100);
        ca200=Contar(200);
        ca500=Contar(500);
        ca1000=Contar(1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal2 = new org.edisoncor.gui.panel.PanelImage();
        btnDepositar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        pnlUsuario = new org.edisoncor.gui.panel.PanelImage();
        txt20 = new app.bolivia.swing.JCTextField();
        pnlUS = new org.edisoncor.gui.panel.PanelImage();
        pnl200 = new org.edisoncor.gui.panel.PanelImage();
        txt200 = new app.bolivia.swing.JCTextField();
        pnlUS5 = new org.edisoncor.gui.panel.PanelImage();
        pnl50 = new org.edisoncor.gui.panel.PanelImage();
        txt50 = new app.bolivia.swing.JCTextField();
        pnlUS6 = new org.edisoncor.gui.panel.PanelImage();
        pnl100 = new org.edisoncor.gui.panel.PanelImage();
        txt100 = new app.bolivia.swing.JCTextField();
        pnlUS8 = new org.edisoncor.gui.panel.PanelImage();
        pnl500 = new org.edisoncor.gui.panel.PanelImage();
        txt500 = new app.bolivia.swing.JCTextField();
        pnlUS9 = new org.edisoncor.gui.panel.PanelImage();
        pnl1000 = new org.edisoncor.gui.panel.PanelImage();
        txt1000 = new app.bolivia.swing.JCTextField();
        pnlUS39 = new org.edisoncor.gui.panel.PanelImage();
        pnlUsuario2 = new org.edisoncor.gui.panel.PanelImage();
        txtCuenta = new app.bolivia.swing.JCTextField();
        pnlUS3 = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/BBVA1.png"))); // NOI18N

        btnDepositar.setBackground(new java.awt.Color(177, 213, 231));
        btnDepositar.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        btnDepositar.setText("Depositar");
        btnDepositar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(177, 213, 231));
        btnInicio.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        pnlUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        txt20.setBorder(null);
        txt20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt20.setPlaceholder("Billetes 20");

        pnlUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/20.png"))); // NOI18N

        javax.swing.GroupLayout pnlUSLayout = new javax.swing.GroupLayout(pnlUS);
        pnlUS.setLayout(pnlUSLayout);
        pnlUSLayout.setHorizontalGroup(
            pnlUSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUSLayout.setVerticalGroup(
            pnlUSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlUsuarioLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(pnlUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlUsuarioLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnl200.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        txt200.setBorder(null);
        txt200.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt200.setPlaceholder("Billetes 200");

        pnlUS5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/200.png"))); // NOI18N

        javax.swing.GroupLayout pnlUS5Layout = new javax.swing.GroupLayout(pnlUS5);
        pnlUS5.setLayout(pnlUS5Layout);
        pnlUS5Layout.setHorizontalGroup(
            pnlUS5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUS5Layout.setVerticalGroup(
            pnlUS5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl200Layout = new javax.swing.GroupLayout(pnl200);
        pnl200.setLayout(pnl200Layout);
        pnl200Layout.setHorizontalGroup(
            pnl200Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl200Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(txt200, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(pnl200Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl200Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(pnlUS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        pnl200Layout.setVerticalGroup(
            pnl200Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl200Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnl200Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl200Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlUS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnl50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        txt50.setBorder(null);
        txt50.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt50.setPlaceholder("Billetes 50");

        pnlUS6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/50.png"))); // NOI18N

        javax.swing.GroupLayout pnlUS6Layout = new javax.swing.GroupLayout(pnlUS6);
        pnlUS6.setLayout(pnlUS6Layout);
        pnlUS6Layout.setHorizontalGroup(
            pnlUS6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUS6Layout.setVerticalGroup(
            pnlUS6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl50Layout = new javax.swing.GroupLayout(pnl50);
        pnl50.setLayout(pnl50Layout);
        pnl50Layout.setHorizontalGroup(
            pnl50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl50Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(pnl50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl50Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(pnlUS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        pnl50Layout.setVerticalGroup(
            pnl50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl50Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnl50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl50Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlUS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnl100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        txt100.setBorder(null);
        txt100.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt100.setPlaceholder("Billetes 100");

        pnlUS8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/100.png"))); // NOI18N

        javax.swing.GroupLayout pnlUS8Layout = new javax.swing.GroupLayout(pnlUS8);
        pnlUS8.setLayout(pnlUS8Layout);
        pnlUS8Layout.setHorizontalGroup(
            pnlUS8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUS8Layout.setVerticalGroup(
            pnlUS8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl100Layout = new javax.swing.GroupLayout(pnl100);
        pnl100.setLayout(pnl100Layout);
        pnl100Layout.setHorizontalGroup(
            pnl100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl100Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(txt100, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(pnl100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl100Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(pnlUS8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        pnl100Layout.setVerticalGroup(
            pnl100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl100Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnl100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl100Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlUS8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnl500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        txt500.setBorder(null);
        txt500.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt500.setPlaceholder("Billetes 500");

        pnlUS9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/500.png"))); // NOI18N

        javax.swing.GroupLayout pnlUS9Layout = new javax.swing.GroupLayout(pnlUS9);
        pnlUS9.setLayout(pnlUS9Layout);
        pnlUS9Layout.setHorizontalGroup(
            pnlUS9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUS9Layout.setVerticalGroup(
            pnlUS9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl500Layout = new javax.swing.GroupLayout(pnl500);
        pnl500.setLayout(pnl500Layout);
        pnl500Layout.setHorizontalGroup(
            pnl500Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl500Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(txt500, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(pnl500Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl500Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(pnlUS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        pnl500Layout.setVerticalGroup(
            pnl500Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl500Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnl500Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl500Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlUS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnl1000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        txt1000.setBorder(null);
        txt1000.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1000.setPlaceholder("Billetes 1000");

        pnlUS39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/1000.png"))); // NOI18N

        javax.swing.GroupLayout pnlUS39Layout = new javax.swing.GroupLayout(pnlUS39);
        pnlUS39.setLayout(pnlUS39Layout);
        pnlUS39Layout.setHorizontalGroup(
            pnlUS39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUS39Layout.setVerticalGroup(
            pnlUS39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl1000Layout = new javax.swing.GroupLayout(pnl1000);
        pnl1000.setLayout(pnl1000Layout);
        pnl1000Layout.setHorizontalGroup(
            pnl1000Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1000Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(txt1000, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(pnl1000Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl1000Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(pnlUS39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        pnl1000Layout.setVerticalGroup(
            pnl1000Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1000Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnl1000Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl1000Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlUS39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        txtCuenta.setBorder(null);
        txtCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCuenta.setPlaceholder("Cuenta");

        pnlUS3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/US.png"))); // NOI18N

        javax.swing.GroupLayout pnlUS3Layout = new javax.swing.GroupLayout(pnlUS3);
        pnlUS3.setLayout(pnlUS3Layout);
        pnlUS3Layout.setHorizontalGroup(
            pnlUS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUS3Layout.setVerticalGroup(
            pnlUS3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlUsuario2Layout = new javax.swing.GroupLayout(pnlUsuario2);
        pnlUsuario2.setLayout(pnlUsuario2Layout);
        pnlUsuario2Layout.setHorizontalGroup(
            pnlUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuario2Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlUsuario2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(pnlUS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(308, Short.MAX_VALUE)))
        );
        pnlUsuario2Layout.setVerticalGroup(
            pnlUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuario2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnlUsuario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlUsuario2Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlUS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlPrincipal2Layout = new javax.swing.GroupLayout(pnlPrincipal2);
        pnlPrincipal2.setLayout(pnlPrincipal2Layout);
        pnlPrincipal2Layout.setHorizontalGroup(
            pnlPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipal2Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(pnlPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipal2Layout.createSequentialGroup()
                        .addGroup(pnlPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipal2Layout.createSequentialGroup()
                                .addComponent(pnl100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl1000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipal2Layout.createSequentialGroup()
                                .addComponent(pnl50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipal2Layout.createSequentialGroup()
                                .addComponent(pnlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipal2Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addGroup(pnlPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipal2Layout.createSequentialGroup()
                        .addComponent(pnlUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        pnlPrincipal2Layout.setVerticalGroup(
            pnlPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipal2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(pnlUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl200, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPrincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl100, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl1000, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        if (new Login().Tipo.equals("U")) {
            new Cliente().setVisible(true);
            this.setVisible(false);
        } else {
            new Admin().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    public int Contar(int n) {
        int a=0;
        try {
            Statement stm = new Conexion().Conexion().createStatement();
            ResultSet rs = stm.executeQuery("select * from Boveda where Denominacion="+n);
            while (rs.next()) {
                a = rs.getInt("Cantidad");
            }
        } catch (Exception e) {
        }
        return a;
    }

    public int saldo() {
        int a = 0;
        try {
            Statement stm = new Conexion().Conexion().createStatement();
            ResultSet rs = stm.executeQuery("select * from Usuarios where Cuenta=\'" + txtCuenta.getText() + "\'");
            while (rs.next()) {
                a = rs.getInt("Saldo");
            }
        } catch (Exception e) {
        }
        return a;
    }

    public boolean verificar() {
        boolean a = false;
        try {
            Statement stm = new Conexion().Conexion().createStatement();
            ResultSet rs = stm.executeQuery("select * from Usuarios where Cuenta=\'" + txtCuenta.getText() + "\'");
            if (rs == null) {
                a = false;
            } else if (txtCuenta.getText().equals("0000000000000000")) {
                a = false;
            } else {
                a = true;
            }
        } catch (Exception e) {
        }
        return a;
    }
    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        if (verificar()) {
            c20 = Integer.parseInt(txt20.getText());
            c50 = Integer.parseInt(txt50.getText());
            c100 = Integer.parseInt(txt100.getText());
            c200 = Integer.parseInt(txt200.getText());
            c500 = Integer.parseInt(txt500.getText());
            c1000 = Integer.parseInt(txt1000.getText());
            int total = ((c20 * 20) + (c50 * 50) + (c100 * 100) + (c200 * 200) + (c500 * 500) + (c1000 * 1000)) + saldo();
            int dialogButton = JOptionPane.showConfirmDialog(null, "<html><h2>Desea Depositar : $" + (total - saldo()) + ".00 a</h2><br><h2>Cuenta : " + txtCuenta.getText() + "</h2></html", "Banco - BBVA", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, icon);
            System.out.println(dialogButton);
            if (dialogButton == 0) {
                if (!txt20.getText().equals("")) {
                    ca20 += Integer.parseInt(txt20.getText());
                }
                if (!txt50.getText().equals("")) {
                    ca50 += Integer.parseInt(txt50.getText());
                }
                if (!txt100.getText().equals("")) {
                    ca100 += Integer.parseInt(txt100.getText());
                }
                if (!txt200.getText().equals("")) {
                    ca200 += Integer.parseInt(txt200.getText());
                }
                if (!txt500.getText().equals("")) {
                    ca500 += Integer.parseInt(txt500.getText());
                }
                if (!txt1000.getText().equals("")) {
                    ca1000 += Integer.parseInt(txt1000.getText());
                }
                try {
                    Statement stm = new Conexion().Conexion().createStatement();
                    stm.executeUpdate("update Usuarios set Saldo=" + total + " where Cuenta=\'" + txtCuenta.getText() + "\'");
                    stm.executeUpdate("update Boveda set Cantidad=" + ca20 + " where Denominacion=20");
                    stm.executeUpdate("update Boveda set Cantidad=" + ca50 + " where Denominacion=50");
                    stm.executeUpdate("update Boveda set Cantidad=" + ca100 + " where Denominacion=100");
                    stm.executeUpdate("update Boveda set Cantidad=" + ca200 + " where Denominacion=200");
                    stm.executeUpdate("update Boveda set Cantidad=" + ca500 + " where Denominacion=500");
                    stm.executeUpdate("update Boveda set Cantidad=" + ca1000 + " where Denominacion=1000");
                    JOptionPane.showMessageDialog(null, "<html><h2>Deposito Realizado</h2></html>",
                            "Banco - BBVA", JOptionPane.INFORMATION_MESSAGE, icon);
                } catch (Exception e) {
                }
                txt20.setText("0");
                txt50.setText("0");
                txt100.setText("0");
                txt200.setText("0");
                txt500.setText("0");
                txt1000.setText("0");
            } else {
                JOptionPane.showMessageDialog(null, "<html><h2>Verifique Datos</h2></html>",
                        "Banco - BBVA", JOptionPane.INFORMATION_MESSAGE, icon);
            }

        } else {
            JOptionPane.showMessageDialog(null, "<html><h2>Cuenta Incorrecta</h2></html>",
                    "Banco - BBVA", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_btnDepositarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnInicio;
    private org.edisoncor.gui.panel.PanelImage pnl100;
    private org.edisoncor.gui.panel.PanelImage pnl1000;
    private org.edisoncor.gui.panel.PanelImage pnl200;
    private org.edisoncor.gui.panel.PanelImage pnl50;
    private org.edisoncor.gui.panel.PanelImage pnl500;
    private org.edisoncor.gui.panel.PanelImage pnlPrincipal2;
    private org.edisoncor.gui.panel.PanelImage pnlUS;
    private org.edisoncor.gui.panel.PanelImage pnlUS3;
    private org.edisoncor.gui.panel.PanelImage pnlUS39;
    private org.edisoncor.gui.panel.PanelImage pnlUS5;
    private org.edisoncor.gui.panel.PanelImage pnlUS6;
    private org.edisoncor.gui.panel.PanelImage pnlUS8;
    private org.edisoncor.gui.panel.PanelImage pnlUS9;
    private org.edisoncor.gui.panel.PanelImage pnlUsuario;
    private org.edisoncor.gui.panel.PanelImage pnlUsuario2;
    private app.bolivia.swing.JCTextField txt100;
    private app.bolivia.swing.JCTextField txt1000;
    private app.bolivia.swing.JCTextField txt20;
    private app.bolivia.swing.JCTextField txt200;
    private app.bolivia.swing.JCTextField txt50;
    private app.bolivia.swing.JCTextField txt500;
    private app.bolivia.swing.JCTextField txtCuenta;
    // End of variables declaration//GEN-END:variables
}
