/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancoso;

import java.awt.Image;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Enrique
 */
public class NIP extends javax.swing.JFrame {

    Icon icon = new ImageIcon(getClass().getResource("IC2.png"));
    public NIP() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("IC.png")).getImage();
        setIconImage(icon);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Banco - BBVA");
        txtCuenta.setText(new Login().Cuenta);
        txtCuenta.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new org.edisoncor.gui.panel.PanelImage();
        pnlNIP = new org.edisoncor.gui.panel.PanelImage();
        txtNuevo = new jpass.JRPasswordField();
        pnlUS2 = new org.edisoncor.gui.panel.PanelImage();
        pnlUsuario = new org.edisoncor.gui.panel.PanelImage();
        txtCuenta = new app.bolivia.swing.JCTextField();
        pnlUS = new org.edisoncor.gui.panel.PanelImage();
        btnInicio = new javax.swing.JButton();
        pnlNIP3 = new org.edisoncor.gui.panel.PanelImage();
        txtAnterior = new jpass.JRPasswordField();
        pnlUS5 = new org.edisoncor.gui.panel.PanelImage();
        btnCambiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/BBVA1.png"))); // NOI18N

        pnlNIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        txtNuevo.setBorder(null);
        txtNuevo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNuevo.setPlaceholder("NIP Nuevo");

        pnlUS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/PW.png"))); // NOI18N

        javax.swing.GroupLayout pnlUS2Layout = new javax.swing.GroupLayout(pnlUS2);
        pnlUS2.setLayout(pnlUS2Layout);
        pnlUS2Layout.setHorizontalGroup(
            pnlUS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUS2Layout.setVerticalGroup(
            pnlUS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlNIPLayout = new javax.swing.GroupLayout(pnlNIP);
        pnlNIP.setLayout(pnlNIPLayout);
        pnlNIPLayout.setHorizontalGroup(
            pnlNIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNIPLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(pnlUS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlNIPLayout.setVerticalGroup(
            pnlNIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNIPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlUS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        txtCuenta.setBorder(null);
        txtCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCuenta.setPlaceholder("Cuenta");

        pnlUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/US.png"))); // NOI18N

        javax.swing.GroupLayout pnlUSLayout = new javax.swing.GroupLayout(pnlUS);
        pnlUS.setLayout(pnlUSLayout);
        pnlUSLayout.setHorizontalGroup(
            pnlUSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUSLayout.setVerticalGroup(
            pnlUSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlUsuarioLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(pnlUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(308, Short.MAX_VALUE)))
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlUsuarioLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnInicio.setBackground(new java.awt.Color(177, 213, 231));
        btnInicio.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        pnlNIP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/CP.png"))); // NOI18N

        txtAnterior.setBorder(null);
        txtAnterior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAnterior.setPlaceholder("NIP Anterior");

        pnlUS5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancoso/PW.png"))); // NOI18N

        javax.swing.GroupLayout pnlUS5Layout = new javax.swing.GroupLayout(pnlUS5);
        pnlUS5.setLayout(pnlUS5Layout);
        pnlUS5Layout.setHorizontalGroup(
            pnlUS5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlUS5Layout.setVerticalGroup(
            pnlUS5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlNIP3Layout = new javax.swing.GroupLayout(pnlNIP3);
        pnlNIP3.setLayout(pnlNIP3Layout);
        pnlNIP3Layout.setHorizontalGroup(
            pnlNIP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNIP3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(pnlUS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlNIP3Layout.setVerticalGroup(
            pnlNIP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNIP3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNIP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlUS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCambiar.setBackground(new java.awt.Color(177, 213, 231));
        btnCambiar.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        btnCambiar.setText("Cambiar");
        btnCambiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlNIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(243, 243, 243))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(pnlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        if(new Login().Tipo.equals("U")){
            new Cliente().setVisible(true);
            this.setVisible(false);
        }else{
            new Admin().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        if(txtAnterior.getText().equals(new Login().NIP)){    
            try {
                Statement stm = new Conexion().Conexion().createStatement();
                stm.executeUpdate("update Usuarios set NIP=\'"+txtNuevo.getText()+"\' where Cuenta=\'"+txtCuenta.getText()+"\'");
                JOptionPane.showMessageDialog(null, "<html><h2>NIP Modificado</h2></html>",
                    "Banco - BBVA", JOptionPane.INFORMATION_MESSAGE, icon);
            } catch (Exception e) {
            }
        }else{
            JOptionPane.showMessageDialog(null, "<html><h2>NIP Anterior Invalido</h2></html>",
                "Banco - BBVA", JOptionPane.INFORMATION_MESSAGE, icon);
        }
        txtAnterior.setText("");
        txtNuevo.setText("");
    }//GEN-LAST:event_btnCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NIP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnInicio;
    private org.edisoncor.gui.panel.PanelImage pnlNIP;
    private org.edisoncor.gui.panel.PanelImage pnlNIP1;
    private org.edisoncor.gui.panel.PanelImage pnlNIP2;
    private org.edisoncor.gui.panel.PanelImage pnlNIP3;
    private org.edisoncor.gui.panel.PanelImage pnlPrincipal;
    private org.edisoncor.gui.panel.PanelImage pnlUS;
    private org.edisoncor.gui.panel.PanelImage pnlUS2;
    private org.edisoncor.gui.panel.PanelImage pnlUS3;
    private org.edisoncor.gui.panel.PanelImage pnlUS4;
    private org.edisoncor.gui.panel.PanelImage pnlUS5;
    private org.edisoncor.gui.panel.PanelImage pnlUsuario;
    private jpass.JRPasswordField txtAnterior;
    private app.bolivia.swing.JCTextField txtCuenta;
    private jpass.JRPasswordField txtNIP1;
    private jpass.JRPasswordField txtNIP2;
    private jpass.JRPasswordField txtNuevo;
    // End of variables declaration//GEN-END:variables
}
